apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
  namespace: nginx-test
  labels:
    app: nginx-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-containers
        image: nginx:latest
        ports:
        - containerPort: 80
