replicaCount: 3

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
